/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetAvailableClients200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAvailableClients200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAvailableClients200Response
        //private GetAvailableClients200Response instance;

        public GetAvailableClients200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetAvailableClients200Response
            //instance = new GetAvailableClients200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAvailableClients200Response
        /// </summary>
        [Fact]
        public void GetAvailableClients200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAvailableClients200Response
            //Assert.IsType<GetAvailableClients200Response>(instance);
        }

        /// <summary>
        /// Test the property 'MediaContainer'
        /// </summary>
        [Fact]
        public void MediaContainerTest()
        {
            // TODO unit test for the property 'MediaContainer'
        }
    }
}
