/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetButlerTasks200ResponseButlerTasksButlerTaskInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetButlerTasks200ResponseButlerTasksButlerTaskInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetButlerTasks200ResponseButlerTasksButlerTaskInner
        //private GetButlerTasks200ResponseButlerTasksButlerTaskInner instance;

        public GetButlerTasks200ResponseButlerTasksButlerTaskInnerTests()
        {
            // TODO uncomment below to create an instance of GetButlerTasks200ResponseButlerTasksButlerTaskInner
            //instance = new GetButlerTasks200ResponseButlerTasksButlerTaskInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetButlerTasks200ResponseButlerTasksButlerTaskInner
        /// </summary>
        [Fact]
        public void GetButlerTasks200ResponseButlerTasksButlerTaskInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetButlerTasks200ResponseButlerTasksButlerTaskInner
            //Assert.IsType<GetButlerTasks200ResponseButlerTasksButlerTaskInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }

        /// <summary>
        /// Test the property 'ScheduleRandomized'
        /// </summary>
        [Fact]
        public void ScheduleRandomizedTest()
        {
            // TODO unit test for the property 'ScheduleRandomized'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
