/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner
        //private GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner instance;

        public GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInnerTests()
        {
            // TODO uncomment below to create an instance of GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner
            //instance = new GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner
        /// </summary>
        [Fact]
        public void GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner
            //Assert.IsType<GetBandwidthStatistics200ResponseMediaContainerStatisticsBandwidthInner>(instance);
        }

        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Fact]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }

        /// <summary>
        /// Test the property 'DeviceID'
        /// </summary>
        [Fact]
        public void DeviceIDTest()
        {
            // TODO unit test for the property 'DeviceID'
        }

        /// <summary>
        /// Test the property 'Timespan'
        /// </summary>
        [Fact]
        public void TimespanTest()
        {
            // TODO unit test for the property 'Timespan'
        }

        /// <summary>
        /// Test the property 'At'
        /// </summary>
        [Fact]
        public void AtTest()
        {
            // TODO unit test for the property 'At'
        }

        /// <summary>
        /// Test the property 'Lan'
        /// </summary>
        [Fact]
        public void LanTest()
        {
            // TODO unit test for the property 'Lan'
        }

        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }
    }
}
