/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetButlerTasks200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetButlerTasks200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetButlerTasks200Response
        //private GetButlerTasks200Response instance;

        public GetButlerTasks200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetButlerTasks200Response
            //instance = new GetButlerTasks200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetButlerTasks200Response
        /// </summary>
        [Fact]
        public void GetButlerTasks200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetButlerTasks200Response
            //Assert.IsType<GetButlerTasks200Response>(instance);
        }

        /// <summary>
        /// Test the property 'ButlerTasks'
        /// </summary>
        [Fact]
        public void ButlerTasksTest()
        {
            // TODO unit test for the property 'ButlerTasks'
        }
    }
}
