/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner
        //private GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner instance;

        public GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInnerTests()
        {
            // TODO uncomment below to create an instance of GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner
            //instance = new GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner
        /// </summary>
        [Fact]
        public void GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner
            //Assert.IsType<GetResourcesStatistics200ResponseMediaContainerStatisticsResourcesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Timespan'
        /// </summary>
        [Fact]
        public void TimespanTest()
        {
            // TODO unit test for the property 'Timespan'
        }

        /// <summary>
        /// Test the property 'At'
        /// </summary>
        [Fact]
        public void AtTest()
        {
            // TODO unit test for the property 'At'
        }

        /// <summary>
        /// Test the property 'HostCpuUtilization'
        /// </summary>
        [Fact]
        public void HostCpuUtilizationTest()
        {
            // TODO unit test for the property 'HostCpuUtilization'
        }

        /// <summary>
        /// Test the property 'ProcessCpuUtilization'
        /// </summary>
        [Fact]
        public void ProcessCpuUtilizationTest()
        {
            // TODO unit test for the property 'ProcessCpuUtilization'
        }

        /// <summary>
        /// Test the property 'HostMemoryUtilization'
        /// </summary>
        [Fact]
        public void HostMemoryUtilizationTest()
        {
            // TODO unit test for the property 'HostMemoryUtilization'
        }

        /// <summary>
        /// Test the property 'ProcessMemoryUtilization'
        /// </summary>
        [Fact]
        public void ProcessMemoryUtilizationTest()
        {
            // TODO unit test for the property 'ProcessMemoryUtilization'
        }
    }
}
