/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetSessions200ResponseMediaContainerMetadataInnerRatingInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessions200ResponseMediaContainerMetadataInnerRatingInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSessions200ResponseMediaContainerMetadataInnerRatingInner
        //private GetSessions200ResponseMediaContainerMetadataInnerRatingInner instance;

        public GetSessions200ResponseMediaContainerMetadataInnerRatingInnerTests()
        {
            // TODO uncomment below to create an instance of GetSessions200ResponseMediaContainerMetadataInnerRatingInner
            //instance = new GetSessions200ResponseMediaContainerMetadataInnerRatingInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSessions200ResponseMediaContainerMetadataInnerRatingInner
        /// </summary>
        [Fact]
        public void GetSessions200ResponseMediaContainerMetadataInnerRatingInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSessions200ResponseMediaContainerMetadataInnerRatingInner
            //Assert.IsType<GetSessions200ResponseMediaContainerMetadataInnerRatingInner>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
