/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerActivities200ResponseMediaContainerActivityInnerContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerActivities200ResponseMediaContainerActivityInnerContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerActivities200ResponseMediaContainerActivityInnerContext
        //private GetServerActivities200ResponseMediaContainerActivityInnerContext instance;

        public GetServerActivities200ResponseMediaContainerActivityInnerContextTests()
        {
            // TODO uncomment below to create an instance of GetServerActivities200ResponseMediaContainerActivityInnerContext
            //instance = new GetServerActivities200ResponseMediaContainerActivityInnerContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerActivities200ResponseMediaContainerActivityInnerContext
        /// </summary>
        [Fact]
        public void GetServerActivities200ResponseMediaContainerActivityInnerContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerActivities200ResponseMediaContainerActivityInnerContext
            //Assert.IsType<GetServerActivities200ResponseMediaContainerActivityInnerContext>(instance);
        }

        /// <summary>
        /// Test the property 'LibrarySectionID'
        /// </summary>
        [Fact]
        public void LibrarySectionIDTest()
        {
            // TODO unit test for the property 'LibrarySectionID'
        }
    }
}
