/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetStatistics200ResponseMediaContainerStatisticsMediaInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatistics200ResponseMediaContainerStatisticsMediaInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStatistics200ResponseMediaContainerStatisticsMediaInner
        //private GetStatistics200ResponseMediaContainerStatisticsMediaInner instance;

        public GetStatistics200ResponseMediaContainerStatisticsMediaInnerTests()
        {
            // TODO uncomment below to create an instance of GetStatistics200ResponseMediaContainerStatisticsMediaInner
            //instance = new GetStatistics200ResponseMediaContainerStatisticsMediaInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStatistics200ResponseMediaContainerStatisticsMediaInner
        /// </summary>
        [Fact]
        public void GetStatistics200ResponseMediaContainerStatisticsMediaInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStatistics200ResponseMediaContainerStatisticsMediaInner
            //Assert.IsType<GetStatistics200ResponseMediaContainerStatisticsMediaInner>(instance);
        }

        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Fact]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }

        /// <summary>
        /// Test the property 'DeviceID'
        /// </summary>
        [Fact]
        public void DeviceIDTest()
        {
            // TODO unit test for the property 'DeviceID'
        }

        /// <summary>
        /// Test the property 'Timespan'
        /// </summary>
        [Fact]
        public void TimespanTest()
        {
            // TODO unit test for the property 'Timespan'
        }

        /// <summary>
        /// Test the property 'At'
        /// </summary>
        [Fact]
        public void AtTest()
        {
            // TODO unit test for the property 'At'
        }

        /// <summary>
        /// Test the property 'MetadataType'
        /// </summary>
        [Fact]
        public void MetadataTypeTest()
        {
            // TODO unit test for the property 'MetadataType'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
    }
}
