/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetStatistics200ResponseMediaContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatistics200ResponseMediaContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStatistics200ResponseMediaContainer
        //private GetStatistics200ResponseMediaContainer instance;

        public GetStatistics200ResponseMediaContainerTests()
        {
            // TODO uncomment below to create an instance of GetStatistics200ResponseMediaContainer
            //instance = new GetStatistics200ResponseMediaContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStatistics200ResponseMediaContainer
        /// </summary>
        [Fact]
        public void GetStatistics200ResponseMediaContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStatistics200ResponseMediaContainer
            //Assert.IsType<GetStatistics200ResponseMediaContainer>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'StatisticsMedia'
        /// </summary>
        [Fact]
        public void StatisticsMediaTest()
        {
            // TODO unit test for the property 'StatisticsMedia'
        }
    }
}
