/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner
        //private GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner instance;

        public GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInnerTests()
        {
            // TODO uncomment below to create an instance of GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner
            //instance = new GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner
        /// </summary>
        [Fact]
        public void GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner
            //Assert.IsType<GetSessions200ResponseMediaContainerMetadataInnerUltraBlurColorsInner>(instance);
        }

        /// <summary>
        /// Test the property 'BottomLeft'
        /// </summary>
        [Fact]
        public void BottomLeftTest()
        {
            // TODO unit test for the property 'BottomLeft'
        }

        /// <summary>
        /// Test the property 'BottomRight'
        /// </summary>
        [Fact]
        public void BottomRightTest()
        {
            // TODO unit test for the property 'BottomRight'
        }

        /// <summary>
        /// Test the property 'TopLeft'
        /// </summary>
        [Fact]
        public void TopLeftTest()
        {
            // TODO unit test for the property 'TopLeft'
        }

        /// <summary>
        /// Test the property 'TopRight'
        /// </summary>
        [Fact]
        public void TopRightTest()
        {
            // TODO unit test for the property 'TopRight'
        }
    }
}
