/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerCapabilities400ResponseErrorsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerCapabilities400ResponseErrorsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerCapabilities400ResponseErrorsInner
        //private GetServerCapabilities400ResponseErrorsInner instance;

        public GetServerCapabilities400ResponseErrorsInnerTests()
        {
            // TODO uncomment below to create an instance of GetServerCapabilities400ResponseErrorsInner
            //instance = new GetServerCapabilities400ResponseErrorsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerCapabilities400ResponseErrorsInner
        /// </summary>
        [Fact]
        public void GetServerCapabilities400ResponseErrorsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerCapabilities400ResponseErrorsInner
            //Assert.IsType<GetServerCapabilities400ResponseErrorsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
