/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetSessions200ResponseMediaContainerMetadataInnerGenreInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessions200ResponseMediaContainerMetadataInnerGenreInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSessions200ResponseMediaContainerMetadataInnerGenreInner
        //private GetSessions200ResponseMediaContainerMetadataInnerGenreInner instance;

        public GetSessions200ResponseMediaContainerMetadataInnerGenreInnerTests()
        {
            // TODO uncomment below to create an instance of GetSessions200ResponseMediaContainerMetadataInnerGenreInner
            //instance = new GetSessions200ResponseMediaContainerMetadataInnerGenreInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSessions200ResponseMediaContainerMetadataInnerGenreInner
        /// </summary>
        [Fact]
        public void GetSessions200ResponseMediaContainerMetadataInnerGenreInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSessions200ResponseMediaContainerMetadataInnerGenreInner
            //Assert.IsType<GetSessions200ResponseMediaContainerMetadataInnerGenreInner>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
    }
}
