/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetSessions200ResponseMediaContainerMetadataInnerPlayer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessions200ResponseMediaContainerMetadataInnerPlayerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSessions200ResponseMediaContainerMetadataInnerPlayer
        //private GetSessions200ResponseMediaContainerMetadataInnerPlayer instance;

        public GetSessions200ResponseMediaContainerMetadataInnerPlayerTests()
        {
            // TODO uncomment below to create an instance of GetSessions200ResponseMediaContainerMetadataInnerPlayer
            //instance = new GetSessions200ResponseMediaContainerMetadataInnerPlayer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSessions200ResponseMediaContainerMetadataInnerPlayer
        /// </summary>
        [Fact]
        public void GetSessions200ResponseMediaContainerMetadataInnerPlayerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSessions200ResponseMediaContainerMetadataInnerPlayer
            //Assert.IsType<GetSessions200ResponseMediaContainerMetadataInnerPlayer>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

        /// <summary>
        /// Test the property 'MachineIdentifier'
        /// </summary>
        [Fact]
        public void MachineIdentifierTest()
        {
            // TODO unit test for the property 'MachineIdentifier'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'PlatformVersion'
        /// </summary>
        [Fact]
        public void PlatformVersionTest()
        {
            // TODO unit test for the property 'PlatformVersion'
        }

        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }

        /// <summary>
        /// Test the property 'RemotePublicAddress'
        /// </summary>
        [Fact]
        public void RemotePublicAddressTest()
        {
            // TODO unit test for the property 'RemotePublicAddress'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Fact]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Local'
        /// </summary>
        [Fact]
        public void LocalTest()
        {
            // TODO unit test for the property 'Local'
        }

        /// <summary>
        /// Test the property 'Relayed'
        /// </summary>
        [Fact]
        public void RelayedTest()
        {
            // TODO unit test for the property 'Relayed'
        }

        /// <summary>
        /// Test the property 'Secure'
        /// </summary>
        [Fact]
        public void SecureTest()
        {
            // TODO unit test for the property 'Secure'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }
    }
}
