/*
 * Plex API
 *
 * Plex OpenAPI Spec 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerAccounts200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerAccounts200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerAccounts200Response
        //private GetServerAccounts200Response instance;

        public GetServerAccounts200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetServerAccounts200Response
            //instance = new GetServerAccounts200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerAccounts200Response
        /// </summary>
        [Fact]
        public void GetServerAccounts200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerAccounts200Response
            //Assert.IsType<GetServerAccounts200Response>(instance);
        }

        /// <summary>
        /// Test the property 'MediaContainer'
        /// </summary>
        [Fact]
        public void MediaContainerTest()
        {
            // TODO unit test for the property 'MediaContainer'
        }
    }
}
