/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetStatistics200ResponseMediaContainerDeviceInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatistics200ResponseMediaContainerDeviceInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStatistics200ResponseMediaContainerDeviceInner
        //private GetStatistics200ResponseMediaContainerDeviceInner instance;

        public GetStatistics200ResponseMediaContainerDeviceInnerTests()
        {
            // TODO uncomment below to create an instance of GetStatistics200ResponseMediaContainerDeviceInner
            //instance = new GetStatistics200ResponseMediaContainerDeviceInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStatistics200ResponseMediaContainerDeviceInner
        /// </summary>
        [Fact]
        public void GetStatistics200ResponseMediaContainerDeviceInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStatistics200ResponseMediaContainerDeviceInner
            //Assert.IsType<GetStatistics200ResponseMediaContainerDeviceInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'ClientIdentifier'
        /// </summary>
        [Fact]
        public void ClientIdentifierTest()
        {
            // TODO unit test for the property 'ClientIdentifier'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
