/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetSessions200ResponseMediaContainerMetadataInnerMediaInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessions200ResponseMediaContainerMetadataInnerMediaInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSessions200ResponseMediaContainerMetadataInnerMediaInner
        //private GetSessions200ResponseMediaContainerMetadataInnerMediaInner instance;

        public GetSessions200ResponseMediaContainerMetadataInnerMediaInnerTests()
        {
            // TODO uncomment below to create an instance of GetSessions200ResponseMediaContainerMetadataInnerMediaInner
            //instance = new GetSessions200ResponseMediaContainerMetadataInnerMediaInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSessions200ResponseMediaContainerMetadataInnerMediaInner
        /// </summary>
        [Fact]
        public void GetSessions200ResponseMediaContainerMetadataInnerMediaInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSessions200ResponseMediaContainerMetadataInnerMediaInner
            //Assert.IsType<GetSessions200ResponseMediaContainerMetadataInnerMediaInner>(instance);
        }

        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Fact]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }

        /// <summary>
        /// Test the property 'AudioChannels'
        /// </summary>
        [Fact]
        public void AudioChannelsTest()
        {
            // TODO unit test for the property 'AudioChannels'
        }

        /// <summary>
        /// Test the property 'AudioCodec'
        /// </summary>
        [Fact]
        public void AudioCodecTest()
        {
            // TODO unit test for the property 'AudioCodec'
        }

        /// <summary>
        /// Test the property 'Bitrate'
        /// </summary>
        [Fact]
        public void BitrateTest()
        {
            // TODO unit test for the property 'Bitrate'
        }

        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Fact]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'VideoCodec'
        /// </summary>
        [Fact]
        public void VideoCodecTest()
        {
            // TODO unit test for the property 'VideoCodec'
        }

        /// <summary>
        /// Test the property 'VideoFrameRate'
        /// </summary>
        [Fact]
        public void VideoFrameRateTest()
        {
            // TODO unit test for the property 'VideoFrameRate'
        }

        /// <summary>
        /// Test the property 'VideoProfile'
        /// </summary>
        [Fact]
        public void VideoProfileTest()
        {
            // TODO unit test for the property 'VideoProfile'
        }

        /// <summary>
        /// Test the property 'VideoResolution'
        /// </summary>
        [Fact]
        public void VideoResolutionTest()
        {
            // TODO unit test for the property 'VideoResolution'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Selected'
        /// </summary>
        [Fact]
        public void SelectedTest()
        {
            // TODO unit test for the property 'Selected'
        }

        /// <summary>
        /// Test the property 'Part'
        /// </summary>
        [Fact]
        public void PartTest()
        {
            // TODO unit test for the property 'Part'
        }
    }
}
