/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerIdentity200ResponseMediaContainer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerIdentity200ResponseMediaContainerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerIdentity200ResponseMediaContainer
        //private GetServerIdentity200ResponseMediaContainer instance;

        public GetServerIdentity200ResponseMediaContainerTests()
        {
            // TODO uncomment below to create an instance of GetServerIdentity200ResponseMediaContainer
            //instance = new GetServerIdentity200ResponseMediaContainer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerIdentity200ResponseMediaContainer
        /// </summary>
        [Fact]
        public void GetServerIdentity200ResponseMediaContainerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerIdentity200ResponseMediaContainer
            //Assert.IsType<GetServerIdentity200ResponseMediaContainer>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Claimed'
        /// </summary>
        [Fact]
        public void ClaimedTest()
        {
            // TODO unit test for the property 'Claimed'
        }

        /// <summary>
        /// Test the property 'MachineIdentifier'
        /// </summary>
        [Fact]
        public void MachineIdentifierTest()
        {
            // TODO unit test for the property 'MachineIdentifier'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
