/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerActivities200ResponseMediaContainerActivityInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerActivities200ResponseMediaContainerActivityInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerActivities200ResponseMediaContainerActivityInner
        //private GetServerActivities200ResponseMediaContainerActivityInner instance;

        public GetServerActivities200ResponseMediaContainerActivityInnerTests()
        {
            // TODO uncomment below to create an instance of GetServerActivities200ResponseMediaContainerActivityInner
            //instance = new GetServerActivities200ResponseMediaContainerActivityInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerActivities200ResponseMediaContainerActivityInner
        /// </summary>
        [Fact]
        public void GetServerActivities200ResponseMediaContainerActivityInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerActivities200ResponseMediaContainerActivityInner
            //Assert.IsType<GetServerActivities200ResponseMediaContainerActivityInner>(instance);
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Cancellable'
        /// </summary>
        [Fact]
        public void CancellableTest()
        {
            // TODO unit test for the property 'Cancellable'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Subtitle'
        /// </summary>
        [Fact]
        public void SubtitleTest()
        {
            // TODO unit test for the property 'Subtitle'
        }

        /// <summary>
        /// Test the property 'Progress'
        /// </summary>
        [Fact]
        public void ProgressTest()
        {
            // TODO unit test for the property 'Progress'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
    }
}
