/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Logship.Plex.OpenApi.Model;
using Logship.Plex.OpenApi.Client;
using System.Reflection;

namespace Logship.Plex.OpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetServerCapabilities400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServerCapabilities400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServerCapabilities400Response
        //private GetServerCapabilities400Response instance;

        public GetServerCapabilities400ResponseTests()
        {
            // TODO uncomment below to create an instance of GetServerCapabilities400Response
            //instance = new GetServerCapabilities400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServerCapabilities400Response
        /// </summary>
        [Fact]
        public void GetServerCapabilities400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServerCapabilities400Response
            //Assert.IsType<GetServerCapabilities400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
