/*
 * Plex Media Server API
 *
 * This is an unofficial OpenAPI specification for the Plex Media Server API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Logship.Plex.OpenApi.Api;
using Logship.Plex.OpenApi.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Logship.Plex.OpenApi.Test.Api
{
    /// <summary>
    ///  Class for testing ServerApi
    /// </summary>
    public sealed class ServerApiTests : ApiTestsBase
    {
        private readonly IServerApi _instance;

        public ServerApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IServerApi>();
        }

        /// <summary>
        /// Test GetAvailableClients
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetAvailableClientsAsyncTest()
        {
            var response = await _instance.GetAvailableClientsAsync();
            var model = response.Ok();
            Assert.IsType<GetAvailableClients200Response>(model);
        }

        /// <summary>
        /// Test GetDevices
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetDevicesAsyncTest()
        {
            var response = await _instance.GetDevicesAsync();
            var model = response.Ok();
            Assert.IsType<GetDevices200Response>(model);
        }

        /// <summary>
        /// Test GetServerCapabilities
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetServerCapabilitiesAsyncTest()
        {
            var response = await _instance.GetServerCapabilitiesAsync();
            var model = response.Ok();
            Assert.IsType<GetServerCapabilities200Response>(model);
        }

        /// <summary>
        /// Test GetServerIdentity
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetServerIdentityAsyncTest()
        {
            var response = await _instance.GetServerIdentityAsync();
            var model = response.Ok();
            Assert.IsType<GetServerIdentity200Response>(model);
        }
    }
}
